email:
  method: 'pop3'
  port: 995
  user_name: '<user>'
  password: '<password>'
  server: 'pop.gmail.com'
  from_address: '<from_address>'
  to_address: '<to_address>'
  subject: 'A change was made'
  ssl: true
webhook:
  port: 1011
  endpoint: '/listener'